### ISSUE TITLE
Adblock blocks the entire page since it detects the adblock-detector library

### ISSUE THREAD

**Issue by raikm** [yutro/adblock-detector#6]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23355792/189853865-8ce5dc10-ee43-483d-8025-a942cb18ca6b.png)

I imported the library in my VueJS App in the root App.vue to detect adblocker. Since I use the library every adblocker detects this library as an ad and blocks the whole page. 

Example code: 

```<script setup lang="ts">

import AdblockDetector from 'adblock-detector'
import { onMounted } from 'vue'


const userHasAdblock = ref(false)

unmounted(async () => {
  userHasAdblock.value = AdblockDetector.detect()
})

</script>```

**Comment by yutro** [comment]
@raikm thanks for letting me know 🍻 will check it this weekend :)

**Comment by raikm** [comment]
FYI: Currently my workaround is to put a try-catch block around it which also gives me the feedback that there is an adblocker active :)

**Comment by yutro** [comment]
So after investigation it turned out that the issue ins not related to library but more the way `Vite` and `ABP` works. When you build package for DEV mode Vite decides to put `adblock-detector` package as separate chunk and by default Vite uses '[name].[hash].[ext]' pattern to name files and then `ABP` comes to the game sees 'adblock-detector' as part of the URL to file and it's in `easy list` as block rule, so package blocked which causes issue and white page.

so to solve issue you need to instruct `Vite` to avoid putting direct name to chunk name to prevent `ABP` filtering this, to do so you can use one of those `rollupOptions`

```
    rollupOptions: {
        output: {
          entryFileNames: `[hash].[ext]`,
          assetFileNames: `[hash].[ext]`,
          chunkFileNames: `[hash].[ext]`,
        }
    }
```

**Comment by raikm** [comment]
Thank you very much for the explanation and investigation!
